### PR TITLE
fix: fixing the word "libaries" to "libraries" in file src/3bc.h

### PR DESCRIPTION
**Pull request by higorbds**
Fixing the word "libaries" to "libraries" in file src/3bc.h.
And resolving issue #181

@RodrigoDornelles

### CODE REVIEW

**Review by RodrigoDornelles — APPROVED** [review]

**Comment by RodrigoDornelles** [comment]
thanks for the contribution, there must be other small grammatical errors feel free to correct them!

**Comment by higorbds** [comment]
> thanks for the contribution, there must be other small grammatical errors feel free to correct them!

Okay, I'm not that good at C, but I can fix these grammatical errors!

**Comment by higorbds** [comment]
Is my first contribution for an open source project of this level, what i do now?

**Comment by RodrigoDornelles** [comment]
> Is my first contribution for an open source project of this level, what i do now? I close pull request?

I meant if you find more grammatical errors in the comments you can contribute again, I'm grateful!

in addition, your contribution helped me with the investigation of a memory problem, because a test failed randomly, something that I had suspected for 2 months but had not happened.

**Comment by higorbds** [comment]
> > Is my first contribution for an open source project of this level, what i do now? I close pull request?
> 
> I meant if you find more grammatical errors in the comments you can contribute again, I'm grateful!
> 
> in addition, your contribution helped me with the investigation of a memory problem, because a test failed randomly, something that I had suspected for 2 months but had not happened.

Yes, after message of TravisCI i understood that the tests failed and that's why the Pull Request not was merged. Thanks!

**Pull request merged**
